import React from "react";
import {Img, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from "remotion";
import {GlossyBalanceScale, GlossyFrictionSlider, GlossyJudyIntro, GlossyRadialDial, KineticTypoLadder, SteppedProgressionStairs} from "../../components/pure_graphics";
import {WordTimestamp} from "../../types";

interface CanvasProps { transcript: WordTimestamp[] }
const Shell: React.FC<{children: React.ReactNode; glow: string}> = ({children, glow}) => <div className="absolute inset-0 overflow-hidden bg-[#030507]"><div className="absolute inset-0" style={{background:`radial-gradient(circle at 50% 43%, ${glow}, transparent 42%),linear-gradient(#06080d,#000 72%)`}}/><div className="absolute inset-x-[80px] top-[115px] bottom-[610px] opacity-[.14]" style={{backgroundImage:"linear-gradient(rgba(255,255,255,.24) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.24) 1px,transparent 1px)",backgroundSize:"80px 80px"}}/><div className="absolute inset-x-0 top-[1260px] h-[3px] bg-white/15"/>{children}</div>;
const Verdict: React.FC<{frame:number;start:number;text:string;color:string}> = ({frame,start,text,color}) => {const {fps}=useVideoConfig();const p=spring({frame:Math.max(0,frame-start),fps,config:{damping:14,stiffness:120}});return <div className="absolute left-1/2 top-[1170px] w-[900px] rounded-[26px] border-2 px-8 py-5 text-center font-mono text-[28px] font-black tracking-[.12em]" style={{borderColor:color,color,background:"rgba(3,5,7,.88)",boxShadow:`0 0 30px ${color}44`,opacity:p,transform:`translateX(-50%) scale(${.9+p*.1})`}}>{text}</div>};

export const GogginsStrategySystemCanvas: React.FC<CanvasProps> = () => {
 const frame=useCurrentFrame(); const {fps}=useVideoConfig();
 if(frame<145){const art=interpolate(frame,[76,120],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <Shell glow="rgba(244,63,94,.20)"><GlossyJudyIntro startFrame={0} exitFrame={104} title="TOUGHNESS ≠ THE WHOLE STORY" titleColor="#fff" glowColor="rgba(244,63,94,.35)" pose="character_pointing.png" theme="dark"/>{frame>76&&<div className="absolute left-1/2 top-[390px] w-[860px] overflow-hidden rounded-[34px] border-2 border-white/30 bg-white shadow-[0_25px_80px_rgba(0,0,0,.8)]" style={{opacity:art,transform:`translateX(-50%) scale(${.94+art*.06})`}}><Img src={staticFile("goggins_strategy_system/assets/scene_illustration.png")} className="h-[480px] w-full object-cover"/></div>}</Shell>}
 if(frame<330)return <Shell glow="rgba(56,189,248,.21)"><KineticTypoLadder leadIn="THE PUBLIC STORY" slamWord="MYTH" punchText="PERMANENTLY FIRED UP" startFrame={145} theme="dark" accentColor="#38bdf8" showSelectionBox showCursor cursorType="arrow" yOffset="10%" align="center"/><div className="absolute left-1/2 top-[570px] -translate-x-1/2"><GlossyFrictionSlider title="MOTIVATION DROPS" startLabel="HYPE" endLabel="SYSTEM" startPercent={88} endPercent={12} accentColor="#38bdf8" glowColor="rgba(56,189,248,.30)" startFrame={175} dragDurationFrames={62} width={850} showCursor showFloorReflection theme="dark"/></div><Verdict frame={frame} start={260} color="#38bdf8" text="TOUGHNESS STARTS IT · STRATEGY SUSTAINS IT"/></Shell>;
 if(frame<570)return <Shell glow="rgba(245,158,11,.22)"><KineticTypoLadder leadIn="WHEN RESISTANCE SAYS STOP" slamWord="EVIDENCE" punchText="OPEN THE COOKIE JAR" startFrame={330} theme="dark" accentColor="#fbbf24" showSelectionBox showCursor cursorType="arrow" yOffset="10%" align="center"/><div className="absolute left-1/2 top-[565px] -translate-x-1/2"><GlossyBalanceScale title="WHAT WINS THE NEXT REP?" leftLabel="FEELING" leftSub="I CAN'T" leftColor="#f43f5e" rightLabel="EVIDENCE" rightSub="I ALREADY DID" rightColor="#fbbf24" winner="right" startFrame={365} width={850} height={470} glowColor="rgba(251,191,36,.28)" showFloorReflection reflectionOpacity={.3}/></div><Verdict frame={frame} start={500} color="#fbbf24" text="PAST WINS → PROOF FOR THE NEXT HARD THING"/></Shell>;
 const dialP=spring({frame:Math.max(0,frame-650),fps,config:{damping:14,stiffness:110}});return <Shell glow="rgba(16,185,129,.23)"><KineticTypoLadder leadIn="MAKE IT REPEATABLE" slamWord="ONE REP" punchText="NOT THE WHOLE MOUNTAIN" startFrame={570} theme="dark" accentColor="#10b981" showSelectionBox showCursor cursorType="arrow" yOffset="10%" align="center"/><div className="absolute left-[80px] top-[590px]"><SteppedProgressionStairs title="" steps={[{id:"one",label:"WRITE 3 WINS"},{id:"two",label:"PICK 1 REP"},{id:"three",label:"DO IT"},{id:"four",label:"REPEAT",isGoal:true}]} orbColor="#fbbf24" startFrame={610} stepDurationFrames={26} width={570} height={420} showFloorReflection theme="dark"/></div><div className="absolute right-[95px] top-[570px]" style={{opacity:dialP}}><GlossyRadialDial title="NEXT ACTION" targetPercent={100} valueText="1 REP" labelText="EXECUTE" accentColor="#10b981" glowColor="rgba(16,185,129,.30)" startFrame={650} size={400} showFloorReflection theme="dark"/></div><Verdict frame={frame} start={750} color="#10b981" text="WRITE THREE WINS · ATTACK THE NEXT REP"/></Shell>;
};
