/**
 * 🎬 Frontier #0: Creative Intelligence Orchestrator — Capability Registry
 * 
 * Machine-readable manifest of all creative frontiers, metadata,
 * component mappings, weights, and constraints.
 */

import { ENABLE_CINEMATIC_CAMERA_V3 } from "../config/features";
import { FrontierCapability, FrontierCode } from "./types";

export const FRONTIER_REGISTRY: Record<FrontierCode, FrontierCapability> = {
  F_BASE: {
    id: "F_BASE",
    code: "F_BASE",
    name: "Baseline Kinetic & Cutout System",
    status: "ACTIVE",
    purpose: "High-contrast semantic cutouts, kinetic typography mutations, and editorial framing.",
    creativeStrengths: [
      "Immediate clarity on 6-inch mobile screens",
      "Razor-sharp 7:1 contrast",
      "Progressive word-level micro-choreography",
      "Real-time text action (slash strikes, highlighters)",
    ],
    bestUseSituations: [
      "Direct cognitive paradoxes and cognitive definitions",
      "Numerical metric readouts and data contrasts",
      "Intimate presenter dialogue and decisive takeaways",
      "Fast punchy scenes requiring zero physics overhead",
    ],
    antiUseSituations: [
      "Scenes requiring macroscopic multi-chamber spatial journeys",
      "Complex physical momentum transfers",
    ],
    dependencies: [
      "components/kinetic_text",
      "components/CinematicIllustrationCard",
      "components/pure_graphics",
      "components/AppleKineticCaptions",
    ],
    exportedComponents: [
      "AnimatedSlashStrike",
      "KineticHighlighter",
      "ConceptKeywordSlam",
      "CinematicIllustrationCard",
      "GlossyJudyIntro",
    ],
    performanceCost: "ZERO",
    complexityWeight: 1.0,
    mobileRisk: "LOW",
    synergisticWith: ["F2", "F6"],
    conflictsWith: [],
    defaultIntensity: "HIGH",
  },

  F0: {
    id: "F0",
    code: "F0",
    name: "Creative Intelligence Orchestrator",
    status: "ACTIVE",
    purpose: "Autonomous decision-making layer selecting the minimum sufficient capability set per scene.",
    creativeStrengths: [
      "Prevents effect soup and visual clutter",
      "Guarantees scene-specific visual metaphors",
      "Enforces mobile legibility and 60 FPS performance",
      "Provides transparent explainability for every selection and rejection",
    ],
    bestUseSituations: ["Every video and scene in RightMotion"],
    antiUseSituations: [],
    dependencies: ["orchestrator/"],
    exportedComponents: [],
    performanceCost: "ZERO",
    complexityWeight: 0.0,
    mobileRisk: "LOW",
    synergisticWith: ["F_BASE", "F1", "F2", "F4", "F5", "F6"],
    conflictsWith: [],
    defaultIntensity: "HIGH",
  },

  F1: {
    id: "F1",
    code: "F1",
    name: "InfiniteWorldCanvas",
    status: "ACTIVE",
    purpose: "Persistent spatial coordinate world with continuous camera travel between concept chambers.",
    creativeStrengths: [
      "Continuous kinematics without disruptive cuts",
      "Spatial anchoring across concept chambers",
      "Macroscopic blueprint reveals (grand zoom pull-back)",
      "Organic camera micro-drift and impact recoil",
    ],
    bestUseSituations: [
      "Multi-stage loops (e.g. Trigger -> Action -> Reward)",
      "Mental architecture with discrete compartments",
      "Deep zoom-ins to microscopic mechanisms",
      "Dramatic macroscopic zoom-outs revealing the full map",
    ],
    antiUseSituations: [
      "Single-subject intimate dialogue",
      "Sharp juxtaposition where a hard cut lands with 3x more force",
      "Short scenes (< 60 frames) where camera flight causes disorientation",
    ],
    dependencies: ["components/camera3d/InfiniteWorldCanvas.tsx"],
    exportedComponents: ["InfiniteWorldCanvas", "WorldEntity"],
    performanceCost: "MEDIUM",
    complexityWeight: 2.5,
    mobileRisk: "MEDIUM",
    synergisticWith: ["F5", "F4", "F6"],
    conflictsWith: ["F3"],
    defaultIntensity: "MEDIUM",
  },

  F2: {
    id: "F2",
    code: "F2",
    name: "Materiality & Physical Semantics",
    status: "ACTIVE",
    purpose: "Material-driven meaning, viscoelastic compressive strain, brittle stress fractures, and ink absorption.",
    creativeStrengths: [
      "Physical consequence made visible through matter deformation",
      "Compressive strain with volume-preserving lateral bulging (Poisson ratio)",
      "Brittle tension crack propagation and structural cleavage",
      "Capillary ink bleed indicating permanent inscription",
    ],
    bestUseSituations: [
      "Accumulating pressure, chronic stress, or unexpressed burden",
      "Structural breaking points (threshold exceeded -> fracture)",
      "Permanent cognitive shifts / irreversible decisions",
    ],
    antiUseSituations: [
      "Pure data/metric comparisons where deformation degrades readability",
      "Airy, lightweight concepts",
    ],
    dependencies: ["components/physics/materiality/"],
    exportedComponents: [
      "ViscoelasticDeformation",
      "OpticallyStableText",
      "StressFractureEngine",
      "CapillaryInkBleed",
    ],
    performanceCost: "MEDIUM",
    complexityWeight: 1.5,
    mobileRisk: "LOW",
    synergisticWith: ["F4", "F_BASE", "F6"],
    conflictsWith: [],
    defaultIntensity: "MEDIUM",
  },

  F3: {
    id: "F3",
    code: "F3",
    name: "Cinematic Camera Language + Depth",
    status: ENABLE_CINEMATIC_CAMERA_V3 ? "ACTIVE" : "DORMANT_EXPERIMENTAL",
    purpose: "Multi-plane depth stratification, near-lens foreground occluders, and optical rack focus.",
    creativeStrengths: [
      "True multi-plane parallax depth (Z-stratification)",
      "Dramatic foreground fly-by occlusion",
      "Optical rack-focus shifting narrative attention",
    ],
    bestUseSituations: [
      "Atmospheric cinematic reveals with deep layered perspective",
    ],
    antiUseSituations: [
      "Currently DORMANT: do not activate in production clips.",
      "High CPU cost during software rendering.",
    ],
    dependencies: [
      "components/camera3d/CinematicDepthWorld.tsx",
      "components/camera3d/ForegroundOccluder.tsx",
      "components/camera3d/RackFocus.tsx",
    ],
    exportedComponents: [
      "CinematicDepthWorld",
      "ForegroundOccluder",
      "RackFocus",
    ],
    performanceCost: "HIGH",
    complexityWeight: 3.0,
    mobileRisk: "HIGH",
    synergisticWith: ["F1"],
    conflictsWith: ["F5"],
    defaultIntensity: "LOW",
  },

  F4: {
    id: "F4",
    code: "F4",
    name: "Semantic Mass & Physical Consequence",
    status: "ACTIVE",
    purpose: "Physical inertia, momentum resistance, closed-form torque balance, and tensile strain dynamics.",
    creativeStrengths: [
      "Causal propagation: action in body A directly tilts or moves body B",
      "Mass-differentiated response (light flutter vs colossal lead thud)",
      "Deterministic closed-form physics (no heavy non-deterministic physics engines)",
      "Dramatic fulcrum balance and cable rupture mechanics",
    ],
    bestUseSituations: [
      "Counterweight concepts (e.g. freedom vs responsibility)",
      "Unbalanced systems, heavy psychological baggage, or friction",
      "Immediate cause-and-effect chains",
    ],
    antiUseSituations: [
      "Purely abstract linguistic or philosophical statements",
      "Scenes already dominated by environmental diorama structures",
    ],
    dependencies: ["components/physics/consequence/"],
    exportedComponents: [
      "SemanticMassNode",
      "KineticFulcrumBeam",
      "TensileStructuralTether",
    ],
    performanceCost: "MEDIUM",
    complexityWeight: 2.0,
    mobileRisk: "MEDIUM",
    synergisticWith: ["F2", "F1", "F6"],
    conflictsWith: ["F5"],
    defaultIntensity: "MEDIUM",
  },

  F5: {
    id: "F5",
    code: "F5",
    name: "Environmental / Diorama Worlds",
    status: "ACTIVE",
    purpose: "Architectural grounding, diorama plinths, monolithic cantilevers, and spatial containment.",
    creativeStrengths: [
      "Definitive spatial ground plane preventing floating/disembodied elements",
      "Architectural weight and structural framing",
      "Environmental thresholds and conduits connecting spaces",
    ],
    bestUseSituations: [
      "Concepts grounded in foundation, habit scaffolding, or boundaries",
      "Spatial dioramas with clear floor/pedestal anchoring",
      "Deep structural metaphors",
    ],
    antiUseSituations: [
      "Fast 1–2 second transition scenes where plinths clutter the canvas",
      "Scenes where F4 fulcrum beams or scales already provide full physical ground",
    ],
    dependencies: ["components/environment/"],
    exportedComponents: [
      "DioramaPlinth",
      "BedrockFoundation",
      "MonolithicCantilever",
      "StructuralTruss",
      "EnvironmentalThreshold",
      "WorldStateConduit",
    ],
    performanceCost: "LOW",
    complexityWeight: 2.0,
    mobileRisk: "MEDIUM",
    synergisticWith: ["F1"],
    conflictsWith: ["F4"],
    defaultIntensity: "LOW",
  },

  F6: {
    id: "F6",
    code: "F6",
    name: "Temporal Manipulation",
    status: "ACTIVE",
    purpose: "FPS-independent harmonic oscillations, dramatic breath-hold freezes, and temporal dilation.",
    creativeStrengths: [
      "The 14s dramatic breath-hold: halts all visual drift for a micro-freeze before epiphany",
      "Precise Hertz-based sinusoidal oscillation unaffected by render framerate",
      "Smooth frame scaling across compositions",
    ],
    bestUseSituations: [
      "The pivotal epiphany moment right before revelation",
      "High-tension vibration (e.g. straining cable or vibrating vocal cords)",
      "Synchronized breathing or circadian rhythms",
    ],
    antiUseSituations: [
      "Standard steady-state narration where artificial time warping causes stutter",
    ],
    dependencies: ["utils/temporal.ts"],
    exportedComponents: [
      "timeSine",
      "timeCos",
      "secToFrames",
      "scaleWaypointsToFps",
      "scaleImpactsToFps",
    ],
    performanceCost: "ZERO",
    complexityWeight: 0.5,
    mobileRisk: "LOW",
    synergisticWith: ["F_BASE", "F1", "F2", "F4"],
    conflictsWith: [],
    defaultIntensity: "MEDIUM",
  },
};
