#!/usr/bin/env python3
"""
🎬 Frontier #0: Creative Intelligence Orchestrator — Python Capability Registry
Authoritative registry defining all frontiers, metadata, weights, and constraints.
"""

from typing import Dict, Any, List

FRONTIER_REGISTRY: Dict[str, Dict[str, Any]] = {
    "F_BASE": {
        "id": "F_BASE",
        "code": "F_BASE",
        "name": "Baseline Kinetic & Cutout System",
        "status": "ACTIVE",
        "purpose": "High-contrast semantic cutouts, kinetic typography mutations, and editorial framing.",
        "creative_strengths": [
            "Immediate clarity on 6-inch mobile screens",
            "Razor-sharp 7:1 contrast",
            "Progressive word-level micro-choreography",
            "Real-time text action (slash strikes, highlighters)",
        ],
        "best_use_situations": [
            "Direct cognitive paradoxes and cognitive definitions",
            "Numerical metric readouts and data contrasts",
            "Intimate presenter dialogue and decisive takeaways",
            "Fast punchy scenes requiring zero physics overhead",
        ],
        "anti_use_situations": [
            "Scenes requiring macroscopic multi-chamber spatial journeys",
            "Complex physical momentum transfers",
        ],
        "dependencies": [
            "components/kinetic_text",
            "components/CinematicIllustrationCard",
            "components/pure_graphics",
            "components/AppleKineticCaptions",
        ],
        "exported_components": [
            "AnimatedSlashStrike",
            "KineticHighlighter",
            "ConceptKeywordSlam",
            "CinematicIllustrationCard",
            "GlossyJudyIntro",
        ],
        "performance_cost": "ZERO",
        "complexity_weight": 1.0,
        "mobile_risk": "LOW",
        "synergistic_with": ["F2", "F6"],
        "conflicts_with": [],
        "default_intensity": "HIGH",
    },
    "F0": {
        "id": "F0",
        "code": "F0",
        "name": "Creative Intelligence Orchestrator",
        "status": "ACTIVE",
        "purpose": "Autonomous decision-making layer selecting the minimum sufficient capability set per scene.",
        "creative_strengths": [
            "Prevents effect soup and visual clutter",
            "Guarantees scene-specific visual metaphors",
            "Enforces mobile legibility and 60 FPS performance",
            "Provides transparent explainability for every selection and rejection",
        ],
        "best_use_situations": ["Every video and scene in RightMotion"],
        "anti_use_situations": [],
        "dependencies": ["orchestrator/"],
        "exported_components": [],
        "performance_cost": "ZERO",
        "complexity_weight": 0.0,
        "mobile_risk": "LOW",
        "synergistic_with": ["F_BASE", "F1", "F2", "F4", "F5", "F6"],
        "conflicts_with": [],
        "default_intensity": "HIGH",
    },
    "F1": {
        "id": "F1",
        "code": "F1",
        "name": "InfiniteWorldCanvas",
        "status": "ACTIVE",
        "purpose": "Persistent spatial coordinate world with continuous camera travel between concept chambers.",
        "creative_strengths": [
            "Continuous kinematics without disruptive cuts",
            "Spatial anchoring across concept chambers",
            "Macroscopic blueprint reveals (grand zoom pull-back)",
            "Organic camera micro-drift and impact recoil",
        ],
        "best_use_situations": [
            "Multi-stage loops (e.g. Trigger -> Action -> Reward)",
            "Mental architecture with discrete compartments",
            "Deep zoom-ins to microscopic mechanisms",
            "Dramatic macroscopic zoom-outs revealing the full map",
        ],
        "anti_use_situations": [
            "Single-subject intimate dialogue",
            "Sharp juxtaposition where a hard cut lands with 3x more force",
            "Short scenes (< 60 frames) where camera flight causes disorientation",
        ],
        "dependencies": ["components/camera3d/InfiniteWorldCanvas.tsx"],
        "exported_components": ["InfiniteWorldCanvas", "WorldEntity"],
        "performance_cost": "MEDIUM",
        "complexity_weight": 2.5,
        "mobile_risk": "MEDIUM",
        "synergistic_with": ["F5", "F4", "F6"],
        "conflicts_with": ["F3"],
        "default_intensity": "MEDIUM",
    },
    "F2": {
        "id": "F2",
        "code": "F2",
        "name": "Materiality & Physical Semantics",
        "status": "ACTIVE",
        "purpose": "Material-driven meaning, viscoelastic compressive strain, brittle stress fractures, and ink absorption.",
        "creative_strengths": [
            "Physical consequence made visible through matter deformation",
            "Compressive strain with volume-preserving lateral bulging (Poisson ratio)",
            "Brittle tension crack propagation and structural cleavage",
            "Capillary ink bleed indicating permanent inscription",
        ],
        "best_use_situations": [
            "Accumulating pressure, chronic stress, or unexpressed burden",
            "Structural breaking points (threshold exceeded -> fracture)",
            "Permanent cognitive shifts / irreversible decisions",
        ],
        "anti_use_situations": [
            "Pure data/metric comparisons where deformation degrades readability",
            "Airy, lightweight concepts",
        ],
        "dependencies": ["components/physics/materiality/"],
        "exported_components": [
            "ViscoelasticDeformation",
            "OpticallyStableText",
            "StressFractureEngine",
            "CapillaryInkBleed",
        ],
        "performance_cost": "MEDIUM",
        "complexity_weight": 1.5,
        "mobile_risk": "LOW",
        "synergistic_with": ["F4", "F_BASE", "F6"],
        "conflicts_with": [],
        "default_intensity": "MEDIUM",
    },
    "F3": {
        "id": "F3",
        "code": "F3",
        "name": "Cinematic Camera Language + Depth",
        "status": "DORMANT_EXPERIMENTAL",
        "purpose": "Multi-plane depth stratification, near-lens foreground occluders, and optical rack focus.",
        "creative_strengths": [
            "True multi-plane parallax depth (Z-stratification)",
            "Dramatic foreground fly-by occlusion",
            "Optical rack-focus shifting narrative attention",
        ],
        "best_use_situations": [
            "Atmospheric cinematic reveals with deep layered perspective",
        ],
        "anti_use_situations": [
            "Currently DORMANT: do not activate in production clips.",
            "High CPU cost during software rendering.",
        ],
        "dependencies": [
            "components/camera3d/CinematicDepthWorld.tsx",
            "components/camera3d/ForegroundOccluder.tsx",
            "components/camera3d/RackFocus.tsx",
        ],
        "exported_components": [
            "CinematicDepthWorld",
            "ForegroundOccluder",
            "RackFocus",
        ],
        "performance_cost": "HIGH",
        "complexity_weight": 3.0,
        "mobile_risk": "HIGH",
        "synergistic_with": ["F1"],
        "conflicts_with": ["F5"],
        "default_intensity": "LOW",
    },
    "F4": {
        "id": "F4",
        "code": "F4",
        "name": "Semantic Mass & Physical Consequence",
        "status": "ACTIVE",
        "purpose": "Physical inertia, momentum resistance, closed-form torque balance, and tensile strain dynamics.",
        "creative_strengths": [
            "Causal propagation: action in body A directly tilts or moves body B",
            "Mass-differentiated response (light flutter vs colossal lead thud)",
            "Deterministic closed-form physics (no heavy physics engines)",
            "Dramatic fulcrum balance and cable rupture mechanics",
        ],
        "best_use_situations": [
            "Counterweight concepts (e.g. freedom vs responsibility)",
            "Unbalanced systems, heavy psychological baggage, or friction",
            "Immediate cause-and-effect chains",
        ],
        "anti_use_situations": [
            "Purely abstract linguistic or philosophical statements",
            "Scenes already dominated by environmental diorama structures",
        ],
        "dependencies": ["components/physics/consequence/"],
        "exported_components": [
            "SemanticMassNode",
            "KineticFulcrumBeam",
            "TensileStructuralTether",
        ],
        "performance_cost": "MEDIUM",
        "complexity_weight": 2.0,
        "mobile_risk": "MEDIUM",
        "synergistic_with": ["F2", "F1", "F6"],
        "conflicts_with": ["F5"],
        "default_intensity": "MEDIUM",
    },
    "F5": {
        "id": "F5",
        "code": "F5",
        "name": "Environmental / Diorama Worlds",
        "status": "ACTIVE",
        "purpose": "Architectural grounding, diorama plinths, monolithic cantilevers, and spatial containment.",
        "creative_strengths": [
            "Definitive spatial ground plane preventing floating/disembodied elements",
            "Architectural weight and structural framing",
            "Environmental thresholds and conduits connecting spaces",
        ],
        "best_use_situations": [
            "Concepts grounded in foundation, habit scaffolding, or boundaries",
            "Spatial dioramas with clear floor/pedestal anchoring",
            "Deep structural metaphors",
        ],
        "anti_use_situations": [
            "Fast 1–2 second transition scenes where plinths clutter the canvas",
            "Scenes where F4 fulcrum beams or scales already provide full physical ground",
        ],
        "dependencies": ["components/environment/"],
        "exported_components": [
            "DioramaPlinth",
            "BedrockFoundation",
            "MonolithicCantilever",
            "StructuralTruss",
            "EnvironmentalThreshold",
            "WorldStateConduit",
        ],
        "performance_cost": "LOW",
        "complexity_weight": 2.0,
        "mobile_risk": "MEDIUM",
        "synergistic_with": ["F1"],
        "conflicts_with": ["F4"],
        "default_intensity": "LOW",
    },
    "F6": {
        "id": "F6",
        "code": "F6",
        "name": "Temporal Manipulation",
        "status": "ACTIVE",
        "purpose": "FPS-independent harmonic oscillations, dramatic breath-hold freezes, and temporal dilation.",
        "creative_strengths": [
            "The 14s dramatic breath-hold: halts all visual drift for a micro-freeze before epiphany",
            "Precise Hertz-based sinusoidal oscillation unaffected by render framerate",
            "Smooth frame scaling across compositions",
        ],
        "best_use_situations": [
            "The pivotal epiphany moment right before revelation",
            "High-tension vibration (e.g. straining cable or vibrating vocal cords)",
            "Synchronized breathing or circadian rhythms",
        ],
        "anti_use_situations": [
            "Standard steady-state narration where artificial time warping causes stutter",
        ],
        "dependencies": ["utils/temporal.ts"],
        "exported_components": [
            "timeSine",
            "timeCos",
            "secToFrames",
            "scaleWaypointsToFps",
            "scaleImpactsToFps",
        ],
        "performance_cost": "ZERO",
        "complexity_weight": 0.5,
        "mobile_risk": "LOW",
        "synergistic_with": ["F_BASE", "F1", "F2", "F4"],
        "conflicts_with": [],
        "default_intensity": "MEDIUM",
    },
    "F7": {
        "id": "F7",
        "code": "F7",
        "name": "Visual State Machines & Causal Storytelling",
        "status": "ACTIVE",
        "purpose": "Discrete state transitions, causal consequence chains, threshold-driven events, and cross-scene narrative memory.",
        "creative_strengths": [
            "Replaces arbitrary timestamps with semantic cause-and-effect relationships",
            "Threshold-driven transitions (e.g. load exceeding limit triggers structural strain or cognitive drain)",
            "Persistent state memory across scene boundaries without reset amnesia",
            "Deterministic pre-resolved timeline guaranteed identical in parallel rendering",
        ],
        "best_use_situations": [
            "Accumulating pressure, chronic stress, or task overload loops",
            "Cause-and-effect chains where event in A triggers mutation in B",
            "Irreversible transformations that must persist across scenes",
            "Systems with clear states: nominal -> strained -> critical -> resolved",
        ],
        "anti_use_situations": [
            "Pure static definition scenes where no transformation occurs",
            "Pure data comparisons where 'DO NOTHING SPECIAL' is superior",
        ],
        "dependencies": ["causal/"],
        "exported_components": [
            "CausalWorld",
            "CausalNode",
            "ThresholdReactor",
            "CausalImpulseConduit",
            "StateInspector",
            "useNodeState",
            "useCausalConsequence",
        ],
        "performance_cost": "LOW",
        "complexity_weight": 1.5,
        "mobile_risk": "LOW",
        "synergistic_with": ["F_BASE", "F1", "F2", "F4", "F5", "F6"],
        "conflicts_with": [],
        "default_intensity": "MEDIUM",
    },
    "F_UBG": {
        "id": "F_UBG",
        "code": "F_UBG",
        "name": "Universal Background Intelligence",
        "status": "ACTIVE",
        "purpose": "Autonomous selection, framing, and layering of reusable physical backgrounds and environments.",
        "creative_strengths": [
            "Provides tactile grounding and cinematic atmosphere",
            "Eliminates sterile white-canvas feeling without adding clutter",
            "Context-aware 9:16 crop and text-safe region alignment",
            "Intelligent rejection when foreground mechanisms need visual calm",
        ],
        "best_use_situations": [
            "Cinematic and philosophical narratives",
            "High-contrast minimalist typography scenes",
            "Material transformations and tactile surfaces",
            "Multi-chapter tonal shifts",
        ],
        "anti_use_situations": [
            "Multi-chamber spatial blueprints (F1) where background textures compete",
            "High-density data/diagram HUDs requiring absolute canvas clarity",
        ],
        "dependencies": ["components/backgrounds/UniversalBackground.tsx"],
        "exported_components": ["UniversalBackground"],
        "performance_cost": "ZERO",
        "complexity_weight": 0.5,
        "mobile_risk": "LOW",
        "synergistic_with": ["F_BASE", "F2", "F4", "F6", "F7"],
        "conflicts_with": [],
        "default_intensity": "MEDIUM",
    },
}


